server:
  port: 8004
  servlet:    context-path: /payment-service

spring:
  application:    name: cloud-payment-provider
  cloud:    zookeeper:      connect-string: localhost:2181  datasource:
    username: root
    password: 123456    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding-utr-8&useSSL=false&serverTimezone=JST
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    