server:
  port: 7001

spring:  application:    name: cloud-eureka-server7001

eureka:  instance:    hostname: eureka7001.com
    # 关闭自我保护
#  server:#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
  client:    fetch-registry: false
    register-with-eureka: false
    service-url:      defaultZone: http://eureka7002.com:7002/eureka #集群模式
      # defaultZone: http://localhost:7001/eureka/ #单机模式
  